[project]
name = "oom_dagster_project"
version = "0.1.0"
description = "Dagster orchestration for the training1 dbt project"
requires-python = ">=3.10,<3.15"
dependencies = [
    "dagster",
    "dagster-cloud",
    "dagster-dbt",
    "dbt-core>=1.12,<1.13",
    "dbt-bigquery>=1.12,<1.13",
]

[project.optional-dependencies]
dev = [
    "dagster-webserver",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "oom_dagster_project.definitions"
code_location_name = "oom_dagster_project"
