models:
  - name: dim_hosts_cleansed
    description: "This table derives data from source src hosts."

    columns:
      - name: host_id
        description: "This represents the host id."
        tests:
          - unique
          - not_null
          - relationships:
              arguments:
                to: ref('src_hosts_old')
                field: host_id

      - name: host_name
        description: "This represents the host name."
        tests:
          
          - not_null

      - name: is_superhost
        description: "This represents if the host is a superhost."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]
                quote: false

      - name: created_at
        tests:
          
          - not_null

      - name: updated_at
        tests:
         
          - not_null